language: scala

jdk: oraclejdk8
sudo: false

env:
  - TRAVIS_NODE_VERSION="10.10.0"

scala: [ 2.12.10, 2.13.1 ]

install:
  - source ./.travis/setNodeVersion.sh

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck test
  # Tricks to avoid unnecessary cache updates, from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
